Disable failing tests for Python 3.7 on Ubuntu
python-trio/trio pull request #2488
Opened 2022-11-29 10:03 UTC by harahu

I was prompted by @pquentin to create a PR along these lines. See: https://github.com/python-trio/trio/pull/2480

We have certain SSL-related tests that are failing with Python 3.7 running on Ubuntu. Disabling them makes some sense, as Python 3.7 is reaching EOL in less than a year.

I'm not sure whether these failures imply that we should drop 3.7 support all together, or that it's just the tests that need updating.

2022-11-29 10:43 UTC, pquentin commented
Maybe we'll need this anyway. Can you please remove the other, irrelevant changes?


> I'm not sure whether these failures imply that we should drop 3.7 support all together, or that it's just the tests that need updating.

We do support Python 3.7, most likely the issue is in the test suite. We also have SSL issues on Python 3.10 unfortunately, and nobody figured out why yet.

2022-11-29 11:47 UTC, harahu commented
> Can you please remove the other, irrelevant changes?

Done.

2022-11-29 13:04 UTC, pquentin commented on trio/tests/test_ssl.py
> +    sys.version_info[0:2] == (3, 7),
```suggestion
    sys.version_info < (3, 8),
```

2022-11-29 15:19 UTC, harahu commented on trio/tests/test_ssl.py
> +    reason="Certain SSL Tests are not passing on Ubuntu while running Python 3.7",
Added a reference to your comment suggesting this PR.

2022-11-30 11:47 UTC, pquentin requested changes

2022-11-30 11:47 UTC, pquentin commented on trio/tests/test_ssl.py
> +)
We finally have an explanation: https://gitter.im/python-trio/general?at=63873971326f06602c7091cc. Here's a better skip:

```suggestion
skip_on_broken_openssl: MarkDecorator = pytest.mark.skipif(
    sys.version_info < (3, 8) and ssl.OPENSSL_VERSION_INFO[0] > 1,
    reason="Python 3.7 does not work with OpenSSL versions higher than 1.X",
)
```

2022-11-30 11:47 UTC, pquentin commented on trio/tests/test_ssl.py
> +@skip_on_python_37_linux
```suggestion
@skip_on_broken_openssl
```

2022-11-30 11:47 UTC, pquentin commented on trio/tests/test_ssl.py
> +@skip_on_python_37_linux
```suggestion
@skip_on_broken_openssl
```

2022-11-30 11:47 UTC, pquentin commented on trio/tests/test_ssl.py
> +@skip_on_python_37_linux
```suggestion
@skip_on_broken_openssl
```

2022-11-30 11:47 UTC, pquentin commented on trio/tests/test_ssl.py
> +@skip_on_python_37_linux
```suggestion
@skip_on_broken_openssl
```

2022-11-30 12:39 UTC, pquentin approved these changes

2022-11-30 12:39 UTC, merged