timeout functions now raise ValueError on NaN inputs
python-trio/trio pull request #2667
Opened 2023-06-23 11:19 UTC by jakkdl

Fixes #2493

Consolidated all `ValueError` tests into a single test.

2023-06-23 22:02 UTC, A5rocks approved these changes
Looks good. 1 genuine comment and 2 filler comments.

2023-06-23 22:02 UTC, A5rocks commented on trio/_timeouts.py
> +        raise ValueError("deadline must not be NaN")
Alternatively, "deadline must be a number" but that's ambiguous w/r/t infinity. I think this error message works best, just leaving this here cause... I don't know why.

2023-06-23 22:27 UTC, A5rocks requested changes
Actually, I just remembered changes like this should *probably* get a newsfragment!

2023-06-24 13:00 UTC, jakkdl commented on trio/_timeouts.py
> +
This sounds like something that can be auto-generated / have the signature displayed in another manner in the doc, once the public interface is fully typed.

2023-06-24 13:07 UTC, jakkdl commented
> Actually, I just remembered changes like this should _probably_ get a newsfragment!

Hah! I've been working so much solely on internal stuff I completely forgot this was a thing, good catch!

Feel free to merge if it looks good otherwise :rocket:

2023-06-24 21:06 UTC, A5rocks approved these changes
Small nitpick. `breaking` *does* feel a bit far out but honestly that is probably the best category.

I'll merge (or you can) after blocking CI is fixed.

2023-06-24 21:06 UTC, A5rocks commented on newsfragments/2493.breaking.rst
> +Timeout functions now raise `ValueError` if passed `nan`. This includes `trio.sleep`, `trio.sleep_until`, `trio.move_on_at`, `trio.move_on_after`, `trio.fail_at` and `trio.fail_after`.
I'd rather "NaN" over "nan"

2023-06-25 08:00 UTC, merged