Minor refactors in _threads.py
python-trio/trio pull request #2871
Opened 2023-11-05 15:57 UTC by richardsheridan

Since I've been staring at the threading code for a long time now, I've found a couple of changes that are probably good for maintainability and good style, but were not a priority for release. I recommend looking at this PR commit by commit rather than as a whole; I'll try to make sure CI gives a green check for each discrete refactor.

2023-11-05 16:37 UTC, richardsheridan commented
Mypy boffins: the diff of 5422f61a doesn't touch the `abandon_on_cancel` variable but somehow mypy can't tell anymore that the variable cannot be None past [line 302](https://github.com/python-trio/trio/blob/5422f61aae54fd179c82da0dcb34babf7c5bc95d/trio/_threads.py#L302).

2023-11-05 23:36 UTC, A5rocks commented
> Mypy boffins: the diff of [5422f61](https://github.com/python-trio/trio/commit/5422f61aae54fd179c82da0dcb34babf7c5bc95d) doesn't touch the `abandon_on_cancel` variable but somehow mypy can't tell anymore that the variable cannot be None past [line 302](https://github.com/python-trio/trio/blob/5422f61aae54fd179c82da0dcb34babf7c5bc95d/trio/_threads.py#L302). Is this a mypy bug? I'll just ignore it for now.

mypy doesn't let you redefine the variable type. however, you can stick a `assert abandon_on_cancel is not None` because mypy narrowing will work.

2023-11-05 23:52 UTC, richardsheridan commented
I'd rather ignore than assert because 

 - if a `None` sneaks through, it likely has the correct semantics, so an assertion would be unnecessary brittleness
 - we can save a bytecode on every function call for something we can determine statically

Happy to hear an argument otherwise though!

2023-11-05 23:59 UTC, A5rocks commented
I don't see why mypy started warning you just now, so that's probably a sign of a mypy bug.

As for adding an `assert`, people can always use `-O` and get rid of them (... assuming trio doesn't rely on `assert`s having side effects, which it really shouldn't) so I regard point 2 as irrelevant and point 1 is impossible AFAIK. But idk if it's worth addressing.

2023-11-06 02:03 UTC, richardsheridan commented
> mypy doesn't let you redefine the variable type.

Actually this was the right answer all along, I just needed a new variable to carry along the narrowed type!

2023-11-10 22:50 UTC, CoolCat467 approved these changes
You are quite right, looking at as one big change is confusing. After going through each commit, this looks great!

2023-11-17 05:42 UTC, CoolCat467 approved these changes

2023-11-18 02:56 UTC, A5rocks requested changes
One small thing I noticed, looks good other than this.

2023-11-18 02:56 UTC, A5rocks commented on src/trio/_threads.py
> +    context.run(current_async_library_cvar.set, None)
I thought we didn't use this anymore. As of https://github.com/python-trio/trio/pull/2700

2023-11-18 02:57 UTC, A5rocks commented on src/trio/_threads.py
> +    context.run(current_async_library_cvar.set, None)
Ohh sorry I should have read the comment better. Ack.

2023-11-18 02:57 UTC, A5rocks approved these changes
Sorry about the confusion, looks good.

2023-11-18 03:25 UTC, CoolCat467 commented
With a second approval, I am going to merge this.

2023-11-18 03:26 UTC, merged