Path decorators: allow empty docstrings to support embedded Python
python-trio/trio pull request #2979
Opened 2024-03-30 00:29 UTC by ameily

I am developing an application that runs on the Windows embedded Python package. It appears that the embedded Python standard library does not include docstrings which means an unhandled exception is raised when importing trio because of a couple `assert X.__doc__ is not None` statements. This PR makes it so `__doc__` is allowed to be `None`.

To test, I am using [Python Windows Embedded 64-bit 3.11.8](https://www.python.org/downloads/release/python-3118/) package. I wrote a small script to show that `__doc__ is None` on every Path function:

```python
import inspect
from pathlib import Path

for name in dir(Path):
    if name.startswith("_"):
        continue

    attr = getattr(Path, name)
    if inspect.isfunction(attr) or inspect.ismethod(attr):
        if attr.__doc__ is None:
            print(f"Path.{name}.__doc__ is None")
```

When I run this through embedded Python I see every function in `Path` has no docstring.

2024-03-30 00:43 UTC, A5rocks commented
IMO we shouldn't set the docstring if there isn't one, rather than acting as though the docstring is blank.

2024-03-30 01:54 UTC, TeamSpen210 commented
That would make sense yes. This might be tricky to test for though - Trio can't work in `-OO` mode, because `pycparser` (imported from `cffi`) needs docstrings to work. But it would be fine if only the standard library is stripped.

2024-04-04 02:49 UTC, A5rocks requested changes
Sorry, I should have marked my previous comment properly. Here it is just as reference:
> IMO we shouldn't set the docstring if there isn't one, rather than acting as though the docstring is blank.

2024-04-07 01:34 UTC, ameily commented on src/trio/_path.py
> +            f"{cleandoc(wrapped.__doc__ or '')}\n"
Sorry about that

2024-04-07 03:12 UTC, A5rocks approved these changes

2024-04-09 10:51 UTC, jakkdl commented
Could add tests which monkeypatch `Path` and then runs the decorator on them, which would appease codecov.

2024-04-12 06:31 UTC, A5rocks commented
I added a test case cause it can be annoying to make them. cc @jakkdl does it look good?

2024-04-12 06:37 UTC, A5rocks commented
@ameily I'm super flakey on these (so you can ignore this if you want) but you don't have a changelog attached! Might be nice to have that.

2024-04-12 08:49 UTC, jakkdl requested changes

2024-04-12 08:49 UTC, jakkdl commented on src/trio/_tests/test_path.py
> +    def func_without_docstring() -> None: ...
```suggestion
    def func_without_docstring() -> None: ...  # pragma: no cover
```

2024-04-12 08:51 UTC, jakkdl commented
> I added a test case cause it can be annoying to make them. cc @jakkdl does it look good?
> 
> (the only iffy bit is passing a sync function to a function that assumes it is async -- but it's not like we run it and we can update that if we ever require passed in functions to satisfy `inspect.iscoroutinefunction`)

looks great! (other than needing a `# pragma: no cover` :P)

2024-04-12 08:51 UTC, jakkdl approved these changes

2024-04-15 10:48 UTC, A5rocks approved these changes

2024-04-15 10:48 UTC, A5rocks commented on newsfragments/2987.issue.rst
> +Fix crash when importing trio in python windows embedded, and other installs that removes docstrings.
```suggestion
Fix crash when importing trio in embedded Python on Windows, and other installs that remove docstrings.
```

Grammar nitpick

2024-04-15 11:00 UTC, merged

2024-04-16 02:10 UTC, CoolCat467 commented on newsfragments/2987.issue.rst
> +Fix crash when importing trio in python windows embedded, and other installs that removes docstrings.
I would have seconded this

2024-04-16 10:59 UTC, jakkdl commented on newsfragments/2987.issue.rst
> +Fix crash when importing trio in python windows embedded, and other installs that removes docstrings.
(I merged the suggestion in b519645)