Constrain dependencies to our requirements.txt file
python-trio/trio pull request #3061
Opened 2024-08-08 01:10 UTC by A5rocks

2024-08-08 01:14 UTC, A5rocks commented
Comparing https://github.com/python-trio/trio/actions/runs/10294036703/job/28491403489 (latest run on main branch) to https://github.com/python-trio/trio/actions/runs/10294184496/job/28491802374?pr=3061 (latest run on this branch):

main branch:
```
  Successfully installed attrs-24.2.0 exceptiongroup-1.2.2 idna-3.7 outcome-1.3.0.post0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.26.2+dev
```

this branch:
```
  Successfully installed attrs-24.1.0 exceptiongroup-1.2.1 idna-3.7 outcome-1.3.0.post0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.26.2+dev
```

Of importance, this branch uses `attrs-24.1.0` rather than the newly released `attrs-24.2.0` (which removes the deprecation warning), as well as an older exceptiongroup, etc. This means that the no-test-deps CI job won't start failing in the middle of nowhere, instead it will only fail for autodeps runs.

2024-08-08 15:04 UTC, CoolCat467 requested changes

2024-08-08 15:04 UTC, CoolCat467 commented on ci.sh
>          python -m pip install -r test-requirements.txt
I think this is what you intended on doing:
```suggestion
        python -m pip install -c test-requirements.txt
```

2024-08-08 15:29 UTC, A5rocks commented
-c just means giving a file as constraints, not installing it as a requirements file

2024-08-13 23:03 UTC, CoolCat467 approved these changes
With information I have learned, I think this looks pretty good

2024-08-21 03:39 UTC, merged