raise BrokenResourceError if lock owner has exited.
python-trio/trio pull request #3080
Opened 2024-09-02 14:36 UTC by jakkdl

Partial fix for #3035 

* Idk if adding `test_lock_multiple_acquire` is very meaningful
* need to add newsfragment

2024-09-03 00:38 UTC, A5rocks requested changes
Can you add a newsfragment?

2024-09-03 00:38 UTC, A5rocks commented on src/trio/_tests/test_sync.py
> +    with pytest.raises(trio.TooSlowError):
How about xfailing this test?

2024-09-03 00:38 UTC, A5rocks commented on src/trio/_sync.py
> +                "Attempted acquire on Lock which will never be released, owner has exited.",
```suggestion
                "Attempted acquire on Lock which will never be released as the owner has exited.",
```

I'm not sure this is the ideal message either way but the alternative I can think of isn't great either: "Deadlock detected: acquiring lock which will never be released."

2024-09-04 14:58 UTC, A5rocks commented
> I'm somewhat concerned about the performance impact of `inspect.getcoroutinestate` in `acquire_nowait()`, which might be fine.

It should only be in the case where we would lock anyways.

> The larger problem is that it only addresses the case where the holding task is _already_ gone at acquire-time; I think we should probably go directly to the general solution of adding a `ParkingLot.mark_resource_broken()` method and using that from Lock.

Yeah, the problem is we can't just add a way to poison a `ParkingLot`, we also need a way to know a `Lock`'s task got ended. We can't use a `weakref.finalizer` because no guarantees on when `Task` gets deleted (it could be stored somewhere else other than `_owner`), so I think we need something in `trio`'s event loop itself.

2024-09-05 14:36 UTC, jakkdl commented
> I'm somewhat concerned about the performance impact of `inspect.getcoroutinestate` in `acquire_nowait()`, which might be fine.

I ran a simple benchmark now and could not detect any difference with or without a call to `inspect.getcoroutinestate`.

> The larger problem is that it only addresses the case where the holding task is _already_ gone at acquire-time; I think we should probably go directly to the general solution of adding a `ParkingLot.mark_resource_broken()` method and using that from Lock.

Yes this PR intentionally only made the easy fix from https://github.com/python-trio/trio/issues/3035#issuecomment-2312328838, but if the full fix turns out doable then we'll close this one.

2024-09-17 14:11 UTC, jakkdl commented
This will probably end up closed in favor of #3081

2024-10-09 06:11 UTC, A5rocks commented
Now unnecessary.

2024-10-09 06:11 UTC, closed without merging